apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: wiki-data-fileshare
    volumeAttributes:
      shareName: wikidata
    nodeStageSecretRef:
      name: azure-files-secret
      namespace: wiki-search
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=185
    - gid=185
    - mfsymlinks
    - cache=strict
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-data-pvc
  namespace: wiki-search
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: wiki-data-pv
  resources:
    requests:
      storage: 100Gi
